"""
Step 4c-ratio: Run noNTL + manual2005 prediction with GAIA built-ratio masks.

This is a thin wrapper around the same modeling idea as step4c, but defaults
to the less-strict raw GAIA ratio mask generated by:
  step4a_resample_raw_gaia_to_grid_ratio.py

Default ratio threshold: 10%.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import geopandas as gpd
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import RandomizedSearchCV, train_test_split


PROJECT_ROOT = Path(__file__).resolve().parents[1]
FEATURE_DIR = PROJECT_ROOT / "data/GEE/shenzhen_features_2000_2020"
GRID_GPKG = PROJECT_ROOT / "data/poi_2020/poi_clean/grid_scored_2020_FD.gpkg"
MANUAL_GRID = PROJECT_ROOT / "data/manual_samples_2005/manual_2005_grid_labels.gpkg"
DEFAULT_GAIA_GRID = PROJECT_ROOT / "data/GAIA_processed/ratio_thr10/grid_gaia_raw_masks_ratio_thr10.gpkg"
OUT_DIR = PROJECT_ROOT / "data/rf_multiyear/noNTL_manual2005_gaia_ratio_thr10"

YEARS = [2000, 2005, 2010, 2015, 2020]
PURE_SUBCLASSES = ["industrial", "residential", "commercial", "public_service"]
RANDOM_STATE = 42
PARAM_DIST = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [10, 20, 30, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5, 10],
    "max_features": ["sqrt", "log2"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="noNTL manual2005 prediction with GAIA ratio mask.")
    parser.add_argument("--feature-dir", type=Path, default=FEATURE_DIR)
    parser.add_argument("--grid-gpkg", type=Path, default=GRID_GPKG)
    parser.add_argument("--grid-layer", default="grid_scored")
    parser.add_argument("--manual-grid-gpkg", type=Path, default=MANUAL_GRID)
    parser.add_argument("--manual-grid-layer", default="manual_2005_grid_labels")
    parser.add_argument("--gaia-grid-gpkg", type=Path, default=DEFAULT_GAIA_GRID)
    parser.add_argument("--gaia-grid-layer", default="grid_gaia_masks")
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    parser.add_argument("--years", default="2000,2005,2010,2015,2020")
    parser.add_argument("--mixed-weight-2020", type=float, default=0.6)
    parser.add_argument("--manual-weight", type=float, default=2.0)
    parser.add_argument("--n-iter", type=int, default=30)
    parser.add_argument("--cv-folds", type=int, default=5)
    parser.add_argument("--n-jobs", type=int, default=-1)
    parser.add_argument("--fast", action="store_true")
    return parser.parse_args()


def parse_years(text: str) -> list[int]:
    return [int(x.strip()) for x in text.split(",") if x.strip()]


def feature_path(feature_dir: Path, year: int) -> Path:
    if year == 2020:
        return feature_dir / "shenzhen_features_2020.csv"
    return feature_dir / f"shenzhen_features_{year}_noNTL.csv"


def feature_cols(feature_dir: Path) -> list[str]:
    cols = pd.read_csv(feature_dir / "shenzhen_features_2020.csv", nrows=0).columns.tolist()
    return [c for c in cols if c != "grid_id" and not c.startswith("NTL_")]


def read_grid(path: Path, layer: str) -> gpd.GeoDataFrame:
    grid = gpd.read_file(path, layer=layer)
    for col in ["ples_class", "ples_subclass"]:
        if col in grid.columns:
            grid[col] = grid[col].astype("string").str.strip()
    return grid


def build_training(args: argparse.Namespace, grid: gpd.GeoDataFrame, cols: list[str]):
    feat2020 = pd.read_csv(args.feature_dir / "shenzhen_features_2020.csv")
    base = feat2020.merge(grid[["grid_id", "ples_class", "ples_subclass"]], on="grid_id", how="inner")
    base = base.dropna(subset=cols).copy()
    base = base[base["ples_class"] != "low_density"].copy()
    base["is_pure"] = base["ples_subclass"].isin(PURE_SUBCLASSES)
    base["is_mixed"] = base["ples_subclass"].str.endswith("_dominated_mixed", na=False)
    base = base[base["is_pure"] | base["is_mixed"]].copy()
    base = base[base["ples_class"].isin(["production", "living"])].copy()
    base["y"] = base["ples_class"]
    base["sample_weight"] = np.where(base["is_pure"], 1.0, args.mixed_weight_2020)
    base["source"] = "poi_2020"

    manual = gpd.read_file(args.manual_grid_gpkg, layer=args.manual_grid_layer)
    feat2005 = pd.read_csv(args.feature_dir / "shenzhen_features_2005_noNTL.csv")
    man = feat2005.merge(manual[["grid_id", "manual_class"]], on="grid_id", how="inner")
    man = man.dropna(subset=cols).copy()
    man = man[man["manual_class"].isin(["production", "living"])].copy()
    man["y"] = man["manual_class"]
    man["sample_weight"] = args.manual_weight
    man["source"] = "manual_2005"

    common = ["grid_id"] + cols + ["y", "sample_weight", "source"]
    train = pd.concat([base[common], man[common]], ignore_index=True)
    return train[cols].to_numpy(), train["y"].to_numpy(), train["sample_weight"].to_numpy(), train


def train_model(args: argparse.Namespace, grid: gpd.GeoDataFrame, cols: list[str]):
    X, y, sw, train = build_training(args, grid, cols)
    X_train, X_test, y_train, y_test, sw_train, sw_test = train_test_split(
        X, y, sw, test_size=0.30, stratify=y, random_state=RANDOM_STATE
    )
    cv = min(args.cv_folds, int(pd.Series(y_train).value_counts().min()))
    n_iter = 3 if args.fast else args.n_iter
    cv = 3 if args.fast else cv
    rf = RandomForestClassifier(class_weight="balanced", random_state=RANDOM_STATE, n_jobs=args.n_jobs)
    search = RandomizedSearchCV(
        rf,
        PARAM_DIST,
        n_iter=n_iter,
        cv=cv,
        scoring="f1_macro",
        n_jobs=args.n_jobs,
        random_state=RANDOM_STATE,
        refit=True,
    )
    search.fit(X_train, y_train, sample_weight=sw_train)
    model = search.best_estimator_
    pred = model.predict(X_test)
    labels = list(model.classes_)
    meta = {
        "model": "PLES_noNTL_manual2005_gaia_ratio",
        "feature_count": len(cols),
        "manual_weight": args.manual_weight,
        "mixed_weight_2020": args.mixed_weight_2020,
        "training_counts": train.groupby(["source", "y"]).size().reset_index(name="n").to_dict(orient="records"),
        "best_params": search.best_params_,
        "cv_best_f1_macro": float(search.best_score_),
        "internal_accuracy": float(accuracy_score(y_test, pred)),
        "internal_f1_macro": float(f1_score(y_test, pred, average="macro")),
        "classes": labels,
        "classification_report": classification_report(y_test, pred, labels=labels, output_dict=True, zero_division=0),
    }
    return model, train, meta


def predict_year(year: int, model: Any, cols: list[str], grid: gpd.GeoDataFrame, gaia: gpd.GeoDataFrame, feature_dir: Path):
    feat = pd.read_csv(feature_path(feature_dir, year))
    df = grid[["grid_id", "geometry"]].merge(feat[["grid_id"] + cols], on="grid_id", how="inner")
    df = df.dropna(subset=cols).copy()
    out = gpd.GeoDataFrame(df[["grid_id", "geometry"]], geometry="geometry", crs=grid.crs)
    out[f"rf_{year}"] = model.predict(df[cols].to_numpy())

    eco_col = f"gaia_ecological_{year}"
    ratio_col = f"gaia_built_ratio_{year}"
    built_col = f"gaia_built_{year}"
    required = ["grid_id", eco_col, ratio_col, built_col]
    missing = [c for c in required if c not in gaia.columns]
    if missing:
        raise ValueError(f"GAIA ratio grid missing columns: {missing}")
    mask = gaia[required].set_index("grid_id").reindex(out["grid_id"])
    out[eco_col] = mask[eco_col].to_numpy()
    out[ratio_col] = mask[ratio_col].to_numpy()
    out[built_col] = mask[built_col].to_numpy()
    out[f"ples_{year}"] = out[f"rf_{year}"].astype("string")
    out.loc[out[eco_col] == 1, f"ples_{year}"] = "ecological"
    return out


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    years = parse_years(args.years)
    grid = read_grid(args.grid_gpkg, args.grid_layer)
    gaia = gpd.read_file(args.gaia_grid_gpkg, layer=args.gaia_grid_layer)
    cols = feature_cols(args.feature_dir)

    model, train, meta = train_model(args, grid, cols)
    meta["gaia_grid_gpkg"] = str(args.gaia_grid_gpkg)
    joblib.dump(model, args.out_dir / "rf_PLES_noNTL_manual2005_gaia_ratio.joblib")
    (args.out_dir / "rf_PLES_noNTL_manual2005_gaia_ratio_metadata.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    train[["grid_id", "y", "sample_weight", "source"]].to_csv(
        args.out_dir / "training_samples_noNTL_manual2005_gaia_ratio.csv",
        index=False,
        encoding="utf-8-sig",
    )

    base = gpd.GeoDataFrame(grid[["grid_id", "geometry"]].copy(), geometry="geometry", crs=grid.crs)
    distributions = []
    for year in years:
        print(f"Predicting {year}...")
        pred = predict_year(year, model, cols, grid, gaia, args.feature_dir)
        aligned = pred.set_index("grid_id").reindex(base["grid_id"])
        for col in [f"rf_{year}", f"gaia_ecological_{year}", f"gaia_built_ratio_{year}", f"gaia_built_{year}", f"ples_{year}"]:
            base[col] = aligned[col].to_numpy()
        dist = base[f"ples_{year}"].value_counts(dropna=False).rename_axis("class").reset_index(name="n")
        dist.insert(0, "year", year)
        distributions.append(dist)

    gpkg = args.out_dir / "shenzhen_ples_multiyear_noNTL_manual2005_gaia_ratio.gpkg"
    if gpkg.exists():
        gpkg.unlink()
    base.to_file(gpkg, layer="ples_multiyear_noNTL_manual2005_gaia_ratio", driver="GPKG")
    pd.concat(distributions, ignore_index=True).to_csv(
        args.out_dir / "distributions_noNTL_manual2005_gaia_ratio.csv",
        index=False,
        encoding="utf-8-sig",
    )
    for y0, y1 in zip(years[:-1], years[1:]):
        pd.crosstab(base[f"ples_{y0}"], base[f"ples_{y1}"], dropna=False).to_csv(
            args.out_dir / f"transition_{y0}_{y1}_noNTL_manual2005_gaia_ratio.csv",
            encoding="utf-8-sig",
        )
    pd.crosstab(base[f"ples_{years[0]}"], base[f"ples_{years[-1]}"], dropna=False).to_csv(
        args.out_dir / f"transition_{years[0]}_{years[-1]}_noNTL_manual2005_gaia_ratio.csv",
        encoding="utf-8-sig",
    )
    pd.DataFrame({"feature": cols, "importance": model.feature_importances_}).sort_values(
        "importance", ascending=False
    ).to_csv(args.out_dir / "feature_importance_noNTL_manual2005_gaia_ratio.csv", index=False, encoding="utf-8-sig")

    print(json.dumps(meta, ensure_ascii=False, indent=2, default=str))
    print(f"Saved: {gpkg}")


if __name__ == "__main__":
    main()
